- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install python3
  apt:
    name: "python3"
    state: present
    update_cache: yes

- name: Install nodejs
  apt:
    name: "nodejs"
    state: present
    update_cache: yes

- name: Install npm
  apt:
    name: "npm"
    state: present

- name: Install "pm2" node.js package globally.
  community.general.npm:
    name: pm2
    global: yes