- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
- name: Install python3, nodejs, npm
  ansible.builtin.apt:
    pkg:
    - python3
    - nodejs
    - npm
- name: Install "pm2" node.js package globally.
  community.general.npm:
    name: pm2
    global: yes