- name: Create deployment directory
  file:
    path: ~/backend-deploy
    state: directory

- name: Deploy
  shell: |
    tar -xf ~/archive.tar.gz -C ~/backend-deploy
    cd ~/backend-deploy
    npm install
    pm2 stop default
    pm2 start npm -- start