- name: Create deployment directory
  file:
    path: ~/backend-deploy
    state: directory

- name: Extract actifact
  unarchive:
    become: true
    src: ~/project/artifact.tar.gz
    dest: ~/backend-deploy

- name: Deploy
  shell: |
    cd ~/backend-deploy
    npm install
    pm2 stop default
    pm2 start npm -- start